### ISSUE TITLE
Feature request: show connected and grouping

### ISSUE THREAD

**Issue by Paxa** [col/GoVPN#1]
Would be nice to see which VPN already connected and split in groups e.g. `Production` and `Others`

**Comment by col** [comment]
Would love to be able to show which are connected. Have not figured out how to do this yet although I have a few ideas that I have not tried yet. 

Grouping is already supported. Open preferences and you can add a group name to each VPN. Not perfect but it works.

**Comment by Paxa** [comment]
Grouping is nice, thanks :)

I found this https://blog.timac.org/2018/0719-vpnstatus/ UI app can show connected IKEv2 VPNs, and there is source code. But I don't know how it works inside
Also some scripts here https://discussions.apple.com/thread/7726810
May be that will help

**Comment by col** [comment]
Thanks for the links! I’ll take a look soon. 👍

**Comment by col** [comment]
The blog post helped a lot so I've added the connected status and the ability to disconnect. 

I've also reached out to @Timac and may even be able to get rid of the hacky Apply Script that GoVPN currently uses to connect and replace it with a direct API call. Unfortunately that'll still take a bit more work as I have to tinker with some more private APIs in order to set the OTP password correctly.
